left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - yumi_joint_1_l
    - yumi_joint_2_l
    - yumi_joint_7_l
    - yumi_joint_3_l
    - yumi_joint_4_l
    - yumi_joint_5_l
    - yumi_joint_6_l
  gains:
    yumi_joint_1_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_7_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_3_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_4_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_5_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_6_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_l_joint
  gains:
    gripper_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_7_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r
  gains:
    yumi_joint_1_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_2_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_7_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_3_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_4_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_6_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_r_joint
  gains:
    gripper_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1